import './globals.css';
import React from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const hi = 0;
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
