name: Test and build
on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and test app
    env:
      CI: true
    #   FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
    #   FIREBASE_ADMIN_CLIENT_EMAIL: ${{secrets.FIREBASE_ADMIN_CLIENT_EMAIL}}
    #   FIREBASE_ADMIN_PRIVATE_KEY: ${{secrets.FIREBASE_ADMIN_PRIVATE_KEY}}
    #   NEXT_PUBLIC_FIREBASE_FRONTEND_API_KEY: ${{secrets.NEXT_PUBLIC_FIREBASE_FRONTEND_API_KEY}}
    #   NEXT_PUBLIC_FIREBASE_FRONTEND_AUTH_DOMAIN: ${{secrets.NEXT_PUBLIC_FIREBASE_FRONTEND_AUTH_DOMAIN}}
    #   NEXT_PUBLIC_FIREBASE_FRONTEND_STORAGE_BUCKET: ${{secrets.NEXT_PUBLIC_FIREBASE_FRONTEND_STORAGE_BUCKET}}
    #   NEXT_PUBLIC_FIREBASE_FRONTEND_MESSAGING_ID: ${{secrets.NEXT_PUBLIC_FIREBASE_FRONTEND_MESSAGING_ID}}
    #   NEXT_PUBLIC_FIREBASE_FRONTEND_APP_ID: ${{secrets.NEXT_PUBLIC_FIREBASE_FRONTEND_APP_ID}}
    #   NEXT_PUBLIC_BACKEND_KEY: ${{secrets.NEXT_PUBLIC_BACKEND_KEY}}

    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: install dependencies
        run: npm ci

      - name: build app
        run: npm run build

      # - name: run tests
      #   run: npm test




